export type LogisticsTri = boolean | null;

export type LogisticsRow = {
  outboundId: string;
  carrierId: string;
  trailerId: string;
  trailerType: string;
  outboundTypeId: string;
  transportationTypeId: string;
  live: LogisticsTri;
  completed: LogisticsTri;
  dispatch: string;
  plannedArrival: string;
  arrived: LogisticsTri;
  ignore: LogisticsTri;
};

/** Static sample rows for the logistics grid. */
export const LOGISTICS_ROWS: LogisticsRow[] = [
  {
    outboundId: "0108156985S",
    carrierId: "FLNA",
    trailerId: "000",
    trailerType: "53SEV",
    outboundTypeId: "bin load",
    transportationTypeId: "truckload",
    live: false,
    completed: false,
    dispatch: "12/30/26",
    plannedArrival: "",
    arrived: true,
    ignore: null,
  },
  {
    outboundId: "009880141S",
    carrierId: "FLNA",
    trailerId: "",
    trailerType: "",
    outboundTypeId: "freightUnit",
    transportationTypeId: "truckload",
    live: false,
    completed: false,
    dispatch: "4/10/26",
    plannedArrival: "",
    arrived: null,
    ignore: false,
  },
  {
    outboundId: "0099120044S",
    carrierId: "FLNA",
    trailerId: "T88421",
    trailerType: "53SEV",
    outboundTypeId: "bin load",
    transportationTypeId: "truckload",
    live: false,
    completed: false,
    dispatch: "4/12/26",
    plannedArrival: "",
    arrived: null,
    ignore: false,
  },
  {
    outboundId: "0099451122S",
    carrierId: "FLNA",
    trailerId: "",
    trailerType: "CC",
    outboundTypeId: "manual",
    transportationTypeId: "truckload",
    live: false,
    completed: false,
    dispatch: "4/14/26",
    plannedArrival: "",
    arrived: null,
    ignore: false,
  },
  {
    outboundId: "0099783301S",
    carrierId: "FLNA",
    trailerId: "A118902",
    trailerType: "CC",
    outboundTypeId: "manual",
    transportationTypeId: "truckload",
    live: false,
    completed: false,
    dispatch: "4/15/26",
    plannedArrival: "",
    arrived: null,
    ignore: false,
  },
  {
    outboundId: "0099904455S",
    carrierId: "FLNA",
    trailerId: "",
    trailerType: "",
    outboundTypeId: "freightUnit",
    transportationTypeId: "truckload",
    live: false,
    completed: false,
    dispatch: "4/16/26",
    plannedArrival: "",
    arrived: null,
    ignore: false,
  },
  {
    outboundId: "0110029905S",
    carrierId: "FLNA",
    trailerId: "",
    trailerType: "CC",
    outboundTypeId: "manual",
    transportationTypeId: "truckload",
    live: false,
    completed: false,
    dispatch: "4/19/26",
    plannedArrival: "",
    arrived: null,
    ignore: false,
  },
  {
    outboundId: "0110187742S",
    carrierId: "FLNA",
    trailerId: "T99001",
    trailerType: "53SEV",
    outboundTypeId: "bin load",
    transportationTypeId: "truckload",
    live: false,
    completed: false,
    dispatch: "4/19/26",
    plannedArrival: "",
    arrived: null,
    ignore: false,
  },
  {
    outboundId: "0110265510S",
    carrierId: "FLNA",
    trailerId: "",
    trailerType: "CC",
    outboundTypeId: "manual",
    transportationTypeId: "truckload",
    live: false,
    completed: false,
    dispatch: "4/20/26",
    plannedArrival: "",
    arrived: null,
    ignore: false,
  },
  {
    outboundId: "0110346625S",
    carrierId: "FLNA",
    trailerId: "A220086",
    trailerType: "CC",
    outboundTypeId: "manual",
    transportationTypeId: "truckload",
    live: false,
    completed: false,
    dispatch: "4/20/26",
    plannedArrival: "",
    arrived: null,
    ignore: false,
  },
  {
    outboundId: "0110412288S",
    carrierId: "FLNA",
    trailerId: "",
    trailerType: "",
    outboundTypeId: "freightUnit",
    transportationTypeId: "truckload",
    live: false,
    completed: false,
    dispatch: "4/21/26",
    plannedArrival: "",
    arrived: null,
    ignore: false,
  },
  {
    outboundId: "0110559014S",
    carrierId: "FLNA",
    trailerId: "B331200",
    trailerType: "53SEV",
    outboundTypeId: "bin load",
    transportationTypeId: "truckload",
    live: false,
    completed: false,
    dispatch: "4/22/26",
    plannedArrival: "",
    arrived: null,
    ignore: false,
  },
];
